server:
  port: 8081

spring:
  application:
    name: api-auth

jwt:
  secret: my-super-ultra-secret-key-for-jwt-auth-256-bit
  issuer: auth-service
  expiration-ms: 3600000

logging:
  level:
    root: INFO